site_name: Dragonfly
repo_url: https://github.com/dragonfly/dragonfly
docs_dir: docs
theme: readthedocs

pages:
- Home: 'index.md'
- Quick Start:
  - 'Installation': 'install.md'
  - 'Getting Started - Command Line': 'getting_started_cli.md'
  - 'Getting Started - Code': 'getting_started_py.md'
- Documentation:
  - 'Main APIs' : 'doc_main_apis.md'
- Tutorial:
  - 'Basic Usage' : 'tut_basic_usage.md'
  - 'Multi-fidelity Optimisation' : 'tut_mf.md'
  - 'Multi-objective Optimisation' : 'tut_moo.md'
  - 'Parallel Bayesian Optimisation' : 'tut_parallel.md'
  - 'Neural Architecture Search' : 'tut_nas.md'
- Advanced Use Cases:
  - 'Defining a Custom Model' : 'tut_custom_model.md'
  - 'A Custom BO Routine' : 'tut_custom_bo.md'
- Miscellaneous:
  - 'FAQ': 'faq.md'
  - 'References': 'references.md'

markdown_extensions:
- admonition
